/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Camera } from './camera';
import { EventBasic } from './event-basic';
import { EventKnownPerson } from './event-known-person';
import { EventMovement } from './event-movement';
import { EventUnknownPerson } from './event-unknown-person';
import { OutdoorEvent } from './outdoor-event';
import { PersonFace } from './person-face';
import { SHomeDPlace } from './shome-dplace';
import { SmokeDetector } from './smoke-detector';
/**
*
*
* @export
* @interface SHomeD
*/
export interface SHomeD {
    /**
     * id of the home
     *
     * @type {string}
     * @memberof SHomeD
     * @example 5954e7f249c75f97428b7b23
     */
    id?: string;
    /**
     * name of the home
     *
     * @type {string}
     * @memberof SHomeD
     * @example Your House
     */
    name?: string;
    /**
     * array of persons in the home
     *
     * @type {Array<PersonFace>}
     * @memberof SHomeD
     */
    person?: Array<PersonFace>;
    /**
     * @type {SHomeDPlace}
     * @memberof SHomeD
     */
    place?: SHomeDPlace;
    /**
     * array of all cameras in the home
     *
     * @type {Array<Camera>}
     * @memberof SHomeD
     */
    camera?: Array<Camera>;
    /**
     * array of all smoke detectors in the home
     *
     * @type {Array<SmokeDetector>}
     * @memberof SHomeD
     */
    smokedetectors?: Array<SmokeDetector>;
    /**
     * @type {Array<EventBasic | EventMovement | EventKnownPerson | EventUnknownPerson | OutdoorEvent>}
     * @memberof SHomeD
     */
    events?: Array<EventBasic | EventMovement | EventKnownPerson | EventUnknownPerson | OutdoorEvent>;
}
