/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface SHomeDPlace
*/
export interface SHomeDPlace {
    /**
     * city name
     *
     * @type {string}
     * @memberof SHomeDPlace
     * @example Paris
     */
    city?: string;
    /**
     * country code
     *
     * @type {string}
     * @memberof SHomeDPlace
     * @example FR
     */
    country?: string;
    /**
     * timezone
     *
     * @type {string}
     * @memberof SHomeDPlace
     * @example Europe/paris
     */
    timezone?: string;
}
