/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface User
*/
export interface User {
    /**
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * @type {string}
     * @memberof User
     * @example fr-FR
     */
    langage?: string;
    /**
     * @type {string}
     * @memberof User
     * @example fr-FR
     */
    locale?: string;
    /**
     * @type {number}
     * @memberof User
     */
    feelLikeAlgorithm?: number;
    /**
     * @type {number}
     * @memberof User
     */
    unitPressure?: number;
    /**
     * @type {number}
     * @memberof User
     */
    unitSystem?: number;
    /**
     * @type {number}
     * @memberof User
     */
    unitWind?: number;
    /**
     * @type {string}
     * @memberof User
     * @example 5c81004fd6e33f0b008b4df2
     */
    id?: string;
}
