/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EventBasic } from './event-basic';
import { EventKnownPerson } from './event-known-person';
import { EventMovement } from './event-movement';
import { EventUnknownPerson } from './event-unknown-person';
import { OutdoorEvent } from './outdoor-event';
 /**
 * 
 *
 * @export
 * @interface BodyEventsListBody
 */
export interface BodyEventsListBody {

    /**
     * @type {Array<EventBasic | EventMovement | EventKnownPerson | EventUnknownPerson | OutdoorEvent>}
     * @memberof BodyEventsListBody
     */
    events_list?: Array<EventBasic | EventMovement | EventKnownPerson | EventUnknownPerson | OutdoorEvent>;
}
