/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SirenD } from './siren-d';
 /**
 * 
 *
 * @export
 * @interface Camera
 */
export interface Camera {

    /**
     * id of the camera
     *
     * @type {string}
     * @memberof Camera
     * @example 70:ee:50:11:xx:xx,
     */
    id?: string;

    /**
     * name of the camera
     *
     * @type {string}
     * @memberof Camera
     * @example NACamera
     */
    type?: string;

    /**
     * @type {string}
     * @memberof Camera
     * @example on
     */
    status?: string;

    /**
     * (restricted return parameter, only returned on OWN camera or with access scope)
     *
     * @type {string}
     * @memberof Camera
     * @example https://prodvpn-eu-5.netatmo.net/10.255.228.11/72xxxxxxxxxxxxxxxxx6f6940/MTYXXXXXXXXDMDoe_XXXXXXXXXbKIYYg,,
     */
    vpnUrl?: string;

    /**
     * @type {boolean}
     * @memberof Camera
     * @example true
     */
    isLocal?: boolean;

    /**
     * @type {string}
     * @memberof Camera
     * @example on
     */
    sdStatus?: string;

    /**
     * @type {string}
     * @memberof Camera
     * @example on
     */
    alimStatus?: string;

    /**
     * @type {string}
     * @memberof Camera
     * @example NameCamera
     */
    name?: string;

    /**
     * array of the module associated to the camera
     *
     * @type {Array<SirenD>}
     * @memberof Camera
     */
    modules?: Array<SirenD>;

    /**
     * true if pincode is required
     *
     * @type {boolean}
     * @memberof Camera
     * @example false
     */
    usePinCode?: boolean;

    /**
     * timestamp of the last installation
     *
     * @type {number}
     * @memberof Camera
     * @example 1549629699
     */
    lastSetup?: number;
}
