/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface EventBasic
 */
export interface EventBasic {

    /**
     * id of the event
     *
     * @type {string}
     * @memberof EventBasic
     * @example 5cdd8075872ee27bc03493cb
     */
    id?: string;

    /**
     * type of events (see written documentation in security section)
     *
     * @type {string}
     * @memberof EventBasic
     * @example connection
     */
    type?: string;

    /**
     * time of occurence of the event
     *
     * @type {number}
     * @memberof EventBasic
     * @example 1556636073
     */
    time?: number;

    /**
     * id of the camera that detected the event
     *
     * @type {string}
     * @memberof EventBasic
     * @example 70:ee:50:xx:xx:xx
     */
    cameraId?: string;

    /**
     * id of the device that detected the event
     *
     * @type {string}
     * @memberof EventBasic
     * @example 70:ee:50:xx:xx:xx
     */
    deviceId?: string;

    /**
     * subtype of SD and Alim events (see written documentation in security section)
     *
     * @type {string}
     * @memberof EventBasic
     * @example 1
     */
    subType?: string;

    /**
     * event description
     *
     * @type {string}
     * @memberof EventBasic
     * @example missing SD card
     */
    message?: string;
}
