/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OutdoorEventlistFilenameVignette
 */
export interface OutdoorEventlistFilenameVignette {

    /**
     * @type {string}
     * @memberof OutdoorEventlistFilenameVignette
     * @example vod\/af74631d-8311-42dc-825b-82e3abeaab09\/events\/c5.jpg
     */
    filename?: string;
}
