/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SbodyHomesdataBodyGlobalInfo
 */
export interface SbodyHomesdataBodyGlobalInfo {

    /**
     * @type {boolean}
     * @memberof SbodyHomesdataBodyGlobalInfo
     * @example true
     */
    showTags?: boolean;
}
