/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SHomeD } from './shome-d';
import { SbodyHomesdataBodyGlobalInfo } from './sbody-homesdata-body-global-info';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface SbodyHomesdataBody
 */
export interface SbodyHomesdataBody {

    /**
     * @type {Array<SHomeD>}
     * @memberof SbodyHomesdataBody
     */
    homes?: Array<SHomeD>;

    /**
     * @type {User}
     * @memberof SbodyHomesdataBody
     */
    user?: User;

    /**
     * @type {SbodyHomesdataBodyGlobalInfo}
     * @memberof SbodyHomesdataBody
     */
    globalInfo?: SbodyHomesdataBodyGlobalInfo;
}
