/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SirenD
 */
export interface SirenD {

    /**
     * @type {string}
     * @memberof SirenD
     * @example 70:ee:50:5b:f0:e9
     */
    id?: string;

    /**
     * @type {string}
     * @memberof SirenD
     * @example NIS
     */
    type?: string;

    /**
     * @type {number}
     * @memberof SirenD
     * @example 84
     */
    batteryPercent?: number;

    /**
     * @type {number}
     * @memberof SirenD
     * @example 68
     */
    rf?: number;

    /**
     * @type {string}
     * @memberof SirenD
     * @example no_news
     */
    status?: string;

    /**
     * @type {string}
     * @memberof SirenD
     * @example on
     */
    monitoring?: string;

    /**
     * @type {string}
     * @memberof SirenD
     * @example battery
     */
    alimSource?: string;

    /**
     * @type {boolean}
     * @memberof SirenD
     */
    tamperDetectionEnabled?: boolean;

    /**
     * @type {string}
     * @memberof SirenD
     * @example Welcome's Siren
     */
    name?: string;
}
