/* tslint:disable */
/* eslint-disable */
/**
 * Legrand - Netatmo - BTicino, Home + Security
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Snapshot
 */
export interface Snapshot {

    /**
     * snapshot id
     *
     * @type {string}
     * @memberof Snapshot
     * @example 5715e16849c75xxxx00000000xxxxx
     */
    id?: string;

    /**
     * @type {number}
     * @memberof Snapshot
     * @example 1
     */
    version?: number;

    /**
     * @type {string}
     * @memberof Snapshot
     * @example 7ac578d05030d0e170643a787ee0a29663dxxx00000xxxxx00000
     */
    key?: string;

    /**
     * @type {string}
     * @memberof Snapshot
     * @example https://netatmocameraimage.blob.core.windows.net/production/1aa0000da9ff73af7d8b4c11d6x0000000e589152cc2xxx4c000006016adb11ef7bf5c8947f76f0ffe00000
     */
    url?: string;
}
