/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
* Weather - Weather station, getstationdata
*
* @export
* @interface DashboardDataWeatherstation
*/
export interface DashboardDataWeatherstation {
    /**
     * timestamp when data was measured
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 1555677739
     */
    timeUtc?: number;
    /**
     * temperature (in °C)
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 23.7
     */
    temperature?: number;
    /**
     * CO2 level (in ppm)
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 967
     */
    cO2?: number;
    /**
     * humidity (in %)
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 41
     */
    humidity?: number;
    /**
     * noise level (in dB)
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 42
     */
    noise?: number;
    /**
     * surface pressure in mbar
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 997.6
     */
    pressure?: number;
    /**
     * sea-level pressure in mbar
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 1017.4
     */
    absolutePressure?: number;
    /**
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 21.2
     */
    minTemp?: number;
    /**
     * maximum temperature measured
     *
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 27.4
     */
    maxTemp?: number;
    /**
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 1555631374
     */
    dateMinTemp?: number;
    /**
     * @type {number}
     * @memberof DashboardDataWeatherstation
     * @example 1555662436
     */
    dateMaxTemp?: number;
    /**
     * trend for the last 12h (up, down, stable)
     *
     * @type {string}
     * @memberof DashboardDataWeatherstation
     * @example up
     */
    tempTrend?: string;
    /**
     * trend for the last 12h (up, down, stable)
     *
     * @type {string}
     * @memberof DashboardDataWeatherstation
     * @example up
     */
    pressureTrend?: string;
}
