/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasureMacAddressNAModule1Res } from './measure-mac-address-namodule1-res';
/**
*
*
* @export
* @interface MeasureMacAddressNAModule1
*/
export interface MeasureMacAddressNAModule1 {
    /**
     * @type {MeasureMacAddressNAModule1Res}
     * @memberof MeasureMacAddressNAModule1
     */
    res?: MeasureMacAddressNAModule1Res;
    /**
     * @type {Array<string>}
     * @memberof MeasureMacAddressNAModule1
     */
    type?: Array<string>;
}
