/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasureMacAddressNAMain } from './measure-mac-address-namain';
import { MeasureMacAddressNAModule1 } from './measure-mac-address-namodule1';
import { MeasureMacAddressNAModule2 } from './measure-mac-address-namodule2';
import { MeasureMacAddressNAModule3 } from './measure-mac-address-namodule3';
/**
*
*
* @export
* @interface Measure
*/
export interface Measure {
    /**
     * @type {MeasureMacAddressNAModule1}
     * @memberof Measure
     */
    macAddressNAModule1?: MeasureMacAddressNAModule1;
    /**
     * @type {MeasureMacAddressNAMain}
     * @memberof Measure
     */
    macAddressNAMain?: MeasureMacAddressNAMain;
    /**
     * @type {MeasureMacAddressNAModule3}
     * @memberof Measure
     */
    macAddressNAModule3?: MeasureMacAddressNAModule3;
    /**
     * @type {MeasureMacAddressNAModule2}
     * @memberof Measure
     */
    macAddressNAModule2?: MeasureMacAddressNAModule2;
}
