/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface MeasureMacAddressNAModule3
*/
export interface MeasureMacAddressNAModule3 {
    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule3
     * @example 0
     */
    rain60min?: number;
    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule3
     * @example 0
     */
    rain24h?: number;
    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule3
     * @example 0
     */
    rainLive?: number;
    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule3
     * @example 1555675431
     */
    rainTimeutc?: number;
}
