/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Measure } from './measure';
import { Place } from './place';
import { PublicDataModuleTypes } from './public-data-module-types';
/**
*
*
* @export
* @interface PublicDataBody
*/
export interface PublicDataBody {
    /**
     * @type {string}
     * @memberof PublicDataBody
     * @example 70:ee:50:22:a3:00
     */
    id?: string;
    /**
     * @type {Place}
     * @memberof PublicDataBody
     */
    place?: Place;
    /**
     * @type {number}
     * @memberof PublicDataBody
     * @example 10
     */
    mark?: number;
    /**
     * @type {Measure}
     * @memberof PublicDataBody
     */
    measures?: Measure;
    /**
     * @type {Array<string>}
     * @memberof PublicDataBody
     */
    modules?: Array<string>;
    /**
     * @type {Array<PublicDataModuleTypes>}
     * @memberof PublicDataBody
     */
    moduleTypes?: Array<PublicDataModuleTypes>;
}
