/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RainModuleDashboardData } from './rain-module-dashboard-data';
/**
* Weather - IN Module, for rain gauge module, getstationdata
*
* @export
* @interface RainModule
*/
export interface RainModule {
    /**
     * @type {string}
     * @memberof RainModule
     * @example 06:00:00:02:47:00
     */
    id?: string;
    /**
     * @type {string}
     * @memberof RainModule
     * @example NAModule3
     */
    type?: string;
    /**
     * @type {string}
     * @memberof RainModule
     * @example Rain gauge
     */
    moduleName?: string;
    /**
     * Array of data measured by the device (e.g. \"Temperature\",\"Humidity\")
     *
     * @type {Array<string>}
     * @memberof RainModule
     */
    dataType?: Array<string>;
    /**
     * timestamp of the last installation
     *
     * @type {number}
     * @memberof RainModule
     * @example 1435834348
     */
    lastSetup?: number;
    /**
     * true if the station connected to Netatmo cloud within the last 4 hours
     *
     * @type {boolean}
     * @memberof RainModule
     * @example true
     */
    reachable?: boolean;
    /**
     * @type {RainModuleDashboardData}
     * @memberof RainModule
     */
    dashboardData?: RainModuleDashboardData;
    /**
     * version of the software
     *
     * @type {number}
     * @memberof RainModule
     * @example 19
     */
    firmware?: number;
    /**
     * timestamp of the last measure update
     *
     * @type {number}
     * @memberof RainModule
     * @example 1555677746
     */
    lastMessage?: number;
    /**
     * timestamp of the last status update
     *
     * @type {number}
     * @memberof RainModule
     * @example 1555677746
     */
    lastSeen?: number;
    /**
     * Current radio status per module. (90=low, 60=highest)
     *
     * @type {number}
     * @memberof RainModule
     * @example 31
     */
    rfStatus?: number;
    /**
     * current battery status per module
     *
     * @type {number}
     * @memberof RainModule
     * @example 5148
     */
    batteryVp?: number;
    /**
     * Percentage of battery remaining (10=low)
     *
     * @type {number}
     * @memberof RainModule
     * @example 58
     */
    batteryPercent?: number;
}
