/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface WindModuleDashboardData
*/
export interface WindModuleDashboardData {
    /**
     * timestamp when data was measured
     *
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 1555677734
     */
    timeUtc?: number;
    /**
     * wind strenght (km/h)
     *
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 2
     */
    windStrength?: number;
    /**
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 75
     */
    windAngle?: number;
    /**
     * gust strengh (km/h)
     *
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 3
     */
    gustStrength?: number;
    /**
     * gust angle
     *
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 75
     */
    gustAngle?: number;
    /**
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 4
     */
    maxWindStr?: number;
    /**
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 100
     */
    maxWindAngle?: number;
    /**
     * @type {number}
     * @memberof WindModuleDashboardData
     * @example 1555673190
     */
    dateMaxWindStr?: number;
}
