/* tslint:disable */
/* eslint-disable */
/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MeasureMacAddressNAModule2
 */
export interface MeasureMacAddressNAModule2 {

    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule2
     * @example 10
     */
    windStrengh?: number;

    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule2
     * @example 259
     */
    windAngle?: number;

    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule2
     * @example 17
     */
    gustStrenght?: number;

    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule2
     * @example 270
     */
    gustAngle?: number;

    /**
     * @type {number}
     * @memberof MeasureMacAddressNAModule2
     * @example 1555675431
     */
    windTimeutc?: number;
}
