/* tslint:disable */
/* eslint-disable */
/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MeasureGet
 */
export interface MeasureGet {

    /**
     * @type {number}
     * @memberof MeasureGet
     * @example 1513295900
     */
    begTime?: number;

    /**
     * @type {number}
     * @memberof MeasureGet
     * @example 1800
     */
    stepTime?: number;

    /**
     * @type {Array<number>}
     * @memberof MeasureGet
     */
    value?: Array<number>;
}
