/* tslint:disable */
/* eslint-disable */
/**
 * Netatmo - Weather
 * This is a sample test for describing NETATMO's APIs with the OAS3 standard definition using swagger.
 *
 * OpenAPI spec version: 1.1.2
 * Contact: contact-api@netatmo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { WindModuleDashboardData } from './wind-module-dashboard-data';
 /**
 * Weather - IN Module, for wind gauge module, getstationdata
 *
 * @export
 * @interface WindModule
 */
export interface WindModule {

    /**
     * @type {string}
     * @memberof WindModule
     * @example 06:00:00:02:47:00
     */
    id?: string;

    /**
     * @type {string}
     * @memberof WindModule
     * @example NAModule2
     */
    type?: string;

    /**
     * @type {string}
     * @memberof WindModule
     * @example Wind Module
     */
    moduleName?: string;

    /**
     * Array of data measured by the device (e.g. \"Temperature\",\"Humidity\")
     *
     * @type {Array<string>}
     * @memberof WindModule
     */
    dataType?: Array<string>;

    /**
     * timestamp of the last installation
     *
     * @type {number}
     * @memberof WindModule
     * @example 1435834348
     */
    lastSetup?: number;

    /**
     * Percentage of battery remaining (10=low)
     *
     * @type {number}
     * @memberof WindModule
     * @example 58
     */
    batteryPercent?: number;

    /**
     * true if the station connected to Netatmo cloud within the last 4 hours
     *
     * @type {boolean}
     * @memberof WindModule
     * @example true
     */
    reachable?: boolean;

    /**
     * version of the software
     *
     * @type {number}
     * @memberof WindModule
     * @example 19
     */
    firmware?: number;

    /**
     * timestamp of the last measure update
     *
     * @type {number}
     * @memberof WindModule
     * @example 1555677746
     */
    lastMessage?: number;

    /**
     * timestamp of the last status update
     *
     * @type {number}
     * @memberof WindModule
     * @example 1555677746
     */
    lastSeen?: number;

    /**
     * Current radio status per module. (90=low, 60=highest)
     *
     * @type {number}
     * @memberof WindModule
     * @example 31
     */
    rfStatus?: number;

    /**
     * current battery status per module
     *
     * @type {number}
     * @memberof WindModule
     * @example 5148
     */
    batteryVp?: number;

    /**
     * @type {WindModuleDashboardData}
     * @memberof WindModule
     */
    dashboardData?: WindModuleDashboardData;
}
